ANZ: str = "RP-HUAWEI-BBIP-AGREGACION-ENLACES-UPLINK-ANZOATEGUI"
BOL: str = "RP-HUAWEI-BBIP-AGREGACION-ENLACES-UPLINK-BOLEITA"
BTO: str = "RP-HUAWEI-BBIP-AGREGACION-ENLACES-UPLINK-BARQUISIMETO"
CHC: str = "RP-HUAWEI-BBIP-AGREGACION-ENLACES-UPLINK-CHACAO"
CNT: str = "RP-HUAWEI-BBIP-AGREGACION-ENLACES-UPLINK-CNT"
LMS: str = "RP-HUAWEI-BBIP-AGREGACION-ENLACES-UPLINK-MERCEDES"
MAD: str = "RP-HUAWEI-BBIP-AGREGACION-ENLACES-UPLINK-MADERERO"
MAY: str = "RP-HUAWEI-BBIP-AGREGACION-ENLACES-UPLINK-MARACAY"
MBO: str = "RP-HUAWEI-BBIP-AGREGACION-ENLACES-UPLINK-MARACAIBO"
MIL: str = "RP-HUAWEI-BBIP-AGREGACION-ENLACES-UPLINK-VALENCIA"
POD: str = "RP-HUAWEI-BBIP-AGREGACION-ENLACES-UPLINK-PUERTO-ORDAZ"
SCR: str = "RP-HUAWEI-BBIP-AGREGACION-ENLACES-UPLINK-SAN-CRISTOBAL"


