from .generate import clients_by_BRAS_and_state
from .generate import adsl_clients_by_BRAS_and_state
from .generate import mdu_clients_by_BRAS_and_state
from .generate import total_comsuption_by_state