BRAS = "BRAS"
STATE = "Estado"
CLIENTS = "Clientes"
CONSUMPTION = "Consumo"
TOTAL_BY_BRAS = "Total por Agregador"
TOTAL_BY_STATE = "Total por Estado"
TOTAL_BY_USAGE = "Total de Consumo por Estado"

CLIENTS_ADSL = "Clientes ADSL"
CONSUMPTION_ADSL = "Consumo ADSL"
CLIENTS_MDU = "Clientes MDU"    
CONSUMPTION_MDU = "Consumo MDU"
CLIENTS_OLT = "Clientes OLT"
CONSUMPTION_OLT = "Consumo OLT"