states = [
    "Amazonas", 
    "Anzoategui", 
    "Apure", 
    "Aragua",
    "Barinas", 
    "Bolivar", 
    "Carabobo", 
    "Cojedes", 
    "Delta Amacuro",
    "Dependencias Federales",
    "Distrito Capital",
    "Falcon", 
    "Guarico",
    "La Guaira", 
    "Lara", 
    "Merida", 
    "Miranda", 
    "Monagas",
    "Nueva Esparta", 
    "Portuguesa", 
    "Sucre", 
    "Tachira", 
    "Trujillo", 
    "Yaracuy", 
    "Zulia"
]
