name: Run Python Unit Tests

on: 
  pull_request:
    branches:
      - main
      - develop

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Set testing environment
        run: echo "URI=mongodb://localhost:27017/unittest_oltraffic_db" >> .env.testing

      - name: Run unit tests
        run: |
          python -m unittest state_consumption.test.process_test
          python -m unittest state_consumption.test.report_test
